apiVersion: apps/v1
kind: Deployment
metadata:
  name: flotix/api-rest-ovh-iot
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1 
        ports:
        - containerPort: 81
    env:
      - name: TOKEN_ID
        value: "foo"
      - name: TOKEN_KEY
        value: "bar"