apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-ovh-iot
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        env:
        - name: TOKEN_ID
          value: "foo"
        - name: TOKEN_KEY
          value: "bar"        
        resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 200Mi 
        ports:
        - containerPort: 81
      