name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v3
      with:
      # version: '<version>' # default is latest stable
      id: install
    steps:
      - uses: actions/checkout@v3
      - name: Run application
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl",
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl,

          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip",
          unzip awscliv2.zip,
          ./aws/install,
          aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name),
          kubectl cluster-info,
          kubectl apply -f gazin_service.yaml,
          kubectl apply -f gazin_application.yaml,
          kubectl apply -f gazin_hpa.yaml,
          kubectl apply -f gazin_ingress.yaml.




