name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run application
        run: |
          aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name),
          kubectl cluster-info,
          kubectl apply -f gazin_application.yaml,
          kubectl apply -f gazin_service.yaml,
          kubectl apply -f gazin_hpa.yaml,
          kubectl apply -f gazin_ingress.yaml.

# name: Kubectl Action

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: tale/kubectl-action@v1
#       with:
#         base64-kube-config: ${{ secrets.KUBE_CONFIG }}
#     - run: kubectl get nodes
