name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run application
        run: |
          kubectl apply -f gazin_application.yaml,
          kubectl apply -f gazin_service.yaml,
          kubectl apply -f gazin_ingress.yaml.
